NUM_EPOCHS = 1000  # Number of times to iterate over the full training set
BATCH_SIZE = 128
DEBUG_STEP_SIZE = 50
NUM_CLASSES = 36
CHARACTER_WIDTH = 24
CHARACTER_HEIGHT = 44
CONVERGENCE_THRESHOLD = 0.001
